--
-- PostgreSQL database dump
--

\restrict fIOi76WT2yoeotlMBM4kczfKGj77QVHtCQXfhwYFU0Mlm5QKhEbJe5v8l8rxl5t

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: CambiosEstado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."CambiosEstado" (
    "Id" integer NOT NULL,
    "EstadoNombre" text NOT NULL,
    "FechaHoraFin" timestamp with time zone,
    "FechaHoraInicio" timestamp with time zone NOT NULL,
    "OrdenDeInspeccionNumeroOrden" integer,
    "SismografoIdentificadorSismografo" integer
);


ALTER TABLE public."CambiosEstado" OWNER TO postgres;

--
-- Name: CambiosEstado_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."CambiosEstado" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."CambiosEstado_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Empleados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Empleados" (
    "Mail" text NOT NULL,
    "Apellido" text NOT NULL,
    "Nombre" text NOT NULL,
    "Telefono" text NOT NULL,
    "RolNombre" text NOT NULL
);


ALTER TABLE public."Empleados" OWNER TO postgres;

--
-- Name: EstacionesSismologicas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."EstacionesSismologicas" (
    "CodigoEstacion" integer NOT NULL,
    "DocumentoCertificacionAdq" boolean NOT NULL,
    "FechaSolicitudCertificacion" timestamp with time zone NOT NULL,
    "Latitud" double precision NOT NULL,
    "Nombre" text NOT NULL,
    "NroCertificacionAdquirida" integer NOT NULL,
    "SismografoIdentificadorSismografo" integer NOT NULL,
    "EmpleadoMail" text,
    "EstadoNombre" text NOT NULL
);


ALTER TABLE public."EstacionesSismologicas" OWNER TO postgres;

--
-- Name: EstacionesSismologicas_CodigoEstacion_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."EstacionesSismologicas" ALTER COLUMN "CodigoEstacion" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."EstacionesSismologicas_CodigoEstacion_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Estados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Estados" (
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL,
    "Ambito" text NOT NULL
);


ALTER TABLE public."Estados" OWNER TO postgres;

--
-- Name: MotivosFueraDeServicio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MotivosFueraDeServicio" (
    "Id" integer NOT NULL,
    "TipoMotivoId" integer NOT NULL,
    "Comentario" text,
    "CambioEstadoId" integer
);


ALTER TABLE public."MotivosFueraDeServicio" OWNER TO postgres;

--
-- Name: MotivosFueraDeServicio_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."MotivosFueraDeServicio" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MotivosFueraDeServicio_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: OrdenesDeInspeccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."OrdenesDeInspeccion" (
    "NumeroOrden" integer NOT NULL,
    "FechaHoraCierre" timestamp with time zone NOT NULL,
    "FechaHoraFinalizacion" timestamp with time zone NOT NULL,
    "FechaHoraInicio" timestamp with time zone NOT NULL,
    "ObservacionCierre" text NOT NULL,
    "EmpleadoMail" text,
    "EstadoNombre" text,
    "EstacionSismologicaCodigoEstacion" integer NOT NULL
);


ALTER TABLE public."OrdenesDeInspeccion" OWNER TO postgres;

--
-- Name: OrdenesDeInspeccion_NumeroOrden_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."OrdenesDeInspeccion" ALTER COLUMN "NumeroOrden" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."OrdenesDeInspeccion_NumeroOrden_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Roles" (
    "Nombre" text NOT NULL,
    "Descripcion" text NOT NULL
);


ALTER TABLE public."Roles" OWNER TO postgres;

--
-- Name: Sesiones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sesiones" (
    "Id" integer NOT NULL,
    "FechaHoraInicio" timestamp with time zone NOT NULL,
    "FechaHoraFin" timestamp with time zone NOT NULL,
    "UsuarioNombreUsuario" text NOT NULL
);


ALTER TABLE public."Sesiones" OWNER TO postgres;

--
-- Name: Sesiones_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sesiones" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sesiones_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Sismografos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sismografos" (
    "IdentificadorSismografo" integer NOT NULL,
    "FechaAdquisicion" timestamp with time zone NOT NULL,
    "NroSerie" integer NOT NULL
);


ALTER TABLE public."Sismografos" OWNER TO postgres;

--
-- Name: Sismografos_IdentificadorSismografo_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Sismografos" ALTER COLUMN "IdentificadorSismografo" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Sismografos_IdentificadorSismografo_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TiposMotivo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TiposMotivo" (
    "Id" integer NOT NULL,
    "Descripcion" text NOT NULL
);


ALTER TABLE public."TiposMotivo" OWNER TO postgres;

--
-- Name: TiposMotivo_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TiposMotivo" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TiposMotivo_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Usuarios" (
    "NombreUsuario" text NOT NULL,
    "Contraseña" text NOT NULL,
    "EmpleadoMail" text
);


ALTER TABLE public."Usuarios" OWNER TO postgres;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: CambiosEstado; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."CambiosEstado" ("Id", "EstadoNombre", "FechaHoraFin", "FechaHoraInicio", "OrdenDeInspeccionNumeroOrden", "SismografoIdentificadorSismografo") FROM stdin;
\.


--
-- Data for Name: Empleados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Empleados" ("Mail", "Apellido", "Nombre", "Telefono", "RolNombre") FROM stdin;
\.


--
-- Data for Name: EstacionesSismologicas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."EstacionesSismologicas" ("CodigoEstacion", "DocumentoCertificacionAdq", "FechaSolicitudCertificacion", "Latitud", "Nombre", "NroCertificacionAdquirida", "SismografoIdentificadorSismografo", "EmpleadoMail", "EstadoNombre") FROM stdin;
\.


--
-- Data for Name: Estados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Estados" ("Nombre", "Descripcion", "Ambito") FROM stdin;
\.


--
-- Data for Name: MotivosFueraDeServicio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."MotivosFueraDeServicio" ("Id", "TipoMotivoId", "Comentario", "CambioEstadoId") FROM stdin;
\.


--
-- Data for Name: OrdenesDeInspeccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."OrdenesDeInspeccion" ("NumeroOrden", "FechaHoraCierre", "FechaHoraFinalizacion", "FechaHoraInicio", "ObservacionCierre", "EmpleadoMail", "EstadoNombre", "EstacionSismologicaCodigoEstacion") FROM stdin;
\.


--
-- Data for Name: Roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Roles" ("Nombre", "Descripcion") FROM stdin;
Administrador	Administrador del sistema
Analista	Analista de datos sísmicos
Responsable de Inspección	Responsable de realizar y supervisar inspecciones
Supervisor	Supervisor de operaciones
Tecnico de Reparaciones	Técnico especializado en reparación de equipos
\.


--
-- Data for Name: Sesiones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sesiones" ("Id", "FechaHoraInicio", "FechaHoraFin", "UsuarioNombreUsuario") FROM stdin;
\.


--
-- Data for Name: Sismografos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Sismografos" ("IdentificadorSismografo", "FechaAdquisicion", "NroSerie") FROM stdin;
\.


--
-- Data for Name: TiposMotivo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TiposMotivo" ("Id", "Descripcion") FROM stdin;
\.


--
-- Data for Name: Usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Usuarios" ("NombreUsuario", "Contraseña", "EmpleadoMail") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251020224411_InitialCreate	9.0.8
\.


--
-- Name: CambiosEstado_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."CambiosEstado_Id_seq"', 1, false);


--
-- Name: EstacionesSismologicas_CodigoEstacion_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."EstacionesSismologicas_CodigoEstacion_seq"', 1, false);


--
-- Name: MotivosFueraDeServicio_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."MotivosFueraDeServicio_Id_seq"', 1, false);


--
-- Name: OrdenesDeInspeccion_NumeroOrden_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."OrdenesDeInspeccion_NumeroOrden_seq"', 1, false);


--
-- Name: Sesiones_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sesiones_Id_seq"', 1, false);


--
-- Name: Sismografos_IdentificadorSismografo_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Sismografos_IdentificadorSismografo_seq"', 1, false);


--
-- Name: TiposMotivo_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TiposMotivo_Id_seq"', 1, false);


--
-- Name: CambiosEstado PK_CambiosEstado; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CambiosEstado"
    ADD CONSTRAINT "PK_CambiosEstado" PRIMARY KEY ("Id");


--
-- Name: Empleados PK_Empleados; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Empleados"
    ADD CONSTRAINT "PK_Empleados" PRIMARY KEY ("Mail");


--
-- Name: EstacionesSismologicas PK_EstacionesSismologicas; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EstacionesSismologicas"
    ADD CONSTRAINT "PK_EstacionesSismologicas" PRIMARY KEY ("CodigoEstacion");


--
-- Name: Estados PK_Estados; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Estados"
    ADD CONSTRAINT "PK_Estados" PRIMARY KEY ("Nombre");


--
-- Name: MotivosFueraDeServicio PK_MotivosFueraDeServicio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MotivosFueraDeServicio"
    ADD CONSTRAINT "PK_MotivosFueraDeServicio" PRIMARY KEY ("Id");


--
-- Name: OrdenesDeInspeccion PK_OrdenesDeInspeccion; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdenesDeInspeccion"
    ADD CONSTRAINT "PK_OrdenesDeInspeccion" PRIMARY KEY ("NumeroOrden");


--
-- Name: Roles PK_Roles; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Roles"
    ADD CONSTRAINT "PK_Roles" PRIMARY KEY ("Nombre");


--
-- Name: Sesiones PK_Sesiones; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sesiones"
    ADD CONSTRAINT "PK_Sesiones" PRIMARY KEY ("Id");


--
-- Name: Sismografos PK_Sismografos; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sismografos"
    ADD CONSTRAINT "PK_Sismografos" PRIMARY KEY ("IdentificadorSismografo");


--
-- Name: TiposMotivo PK_TiposMotivo; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TiposMotivo"
    ADD CONSTRAINT "PK_TiposMotivo" PRIMARY KEY ("Id");


--
-- Name: Usuarios PK_Usuarios; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuarios"
    ADD CONSTRAINT "PK_Usuarios" PRIMARY KEY ("NombreUsuario");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_CambiosEstado_EstadoNombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CambiosEstado_EstadoNombre" ON public."CambiosEstado" USING btree ("EstadoNombre");


--
-- Name: IX_CambiosEstado_OrdenDeInspeccionNumeroOrden; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CambiosEstado_OrdenDeInspeccionNumeroOrden" ON public."CambiosEstado" USING btree ("OrdenDeInspeccionNumeroOrden");


--
-- Name: IX_CambiosEstado_SismografoIdentificadorSismografo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_CambiosEstado_SismografoIdentificadorSismografo" ON public."CambiosEstado" USING btree ("SismografoIdentificadorSismografo");


--
-- Name: IX_Empleados_RolNombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Empleados_RolNombre" ON public."Empleados" USING btree ("RolNombre");


--
-- Name: IX_EstacionesSismologicas_EmpleadoMail; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EstacionesSismologicas_EmpleadoMail" ON public."EstacionesSismologicas" USING btree ("EmpleadoMail");


--
-- Name: IX_EstacionesSismologicas_EstadoNombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EstacionesSismologicas_EstadoNombre" ON public."EstacionesSismologicas" USING btree ("EstadoNombre");


--
-- Name: IX_EstacionesSismologicas_SismografoIdentificadorSismografo; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_EstacionesSismologicas_SismografoIdentificadorSismografo" ON public."EstacionesSismologicas" USING btree ("SismografoIdentificadorSismografo");


--
-- Name: IX_MotivosFueraDeServicio_CambioEstadoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MotivosFueraDeServicio_CambioEstadoId" ON public."MotivosFueraDeServicio" USING btree ("CambioEstadoId");


--
-- Name: IX_MotivosFueraDeServicio_TipoMotivoId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MotivosFueraDeServicio_TipoMotivoId" ON public."MotivosFueraDeServicio" USING btree ("TipoMotivoId");


--
-- Name: IX_OrdenesDeInspeccion_EmpleadoMail; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrdenesDeInspeccion_EmpleadoMail" ON public."OrdenesDeInspeccion" USING btree ("EmpleadoMail");


--
-- Name: IX_OrdenesDeInspeccion_EstacionSismologicaCodigoEstacion; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrdenesDeInspeccion_EstacionSismologicaCodigoEstacion" ON public."OrdenesDeInspeccion" USING btree ("EstacionSismologicaCodigoEstacion");


--
-- Name: IX_OrdenesDeInspeccion_EstadoNombre; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_OrdenesDeInspeccion_EstadoNombre" ON public."OrdenesDeInspeccion" USING btree ("EstadoNombre");


--
-- Name: IX_Sesiones_UsuarioNombreUsuario; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Sesiones_UsuarioNombreUsuario" ON public."Sesiones" USING btree ("UsuarioNombreUsuario");


--
-- Name: IX_Usuarios_EmpleadoMail; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Usuarios_EmpleadoMail" ON public."Usuarios" USING btree ("EmpleadoMail");


--
-- Name: CambiosEstado FK_CambiosEstado_Estados_EstadoNombre; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CambiosEstado"
    ADD CONSTRAINT "FK_CambiosEstado_Estados_EstadoNombre" FOREIGN KEY ("EstadoNombre") REFERENCES public."Estados"("Nombre") ON DELETE CASCADE;


--
-- Name: CambiosEstado FK_CambiosEstado_OrdenesDeInspeccion_OrdenDeInspeccionNumeroOr~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CambiosEstado"
    ADD CONSTRAINT "FK_CambiosEstado_OrdenesDeInspeccion_OrdenDeInspeccionNumeroOr~" FOREIGN KEY ("OrdenDeInspeccionNumeroOrden") REFERENCES public."OrdenesDeInspeccion"("NumeroOrden");


--
-- Name: CambiosEstado FK_CambiosEstado_Sismografos_SismografoIdentificadorSismografo; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."CambiosEstado"
    ADD CONSTRAINT "FK_CambiosEstado_Sismografos_SismografoIdentificadorSismografo" FOREIGN KEY ("SismografoIdentificadorSismografo") REFERENCES public."Sismografos"("IdentificadorSismografo");


--
-- Name: Empleados FK_Empleados_Roles_RolNombre; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Empleados"
    ADD CONSTRAINT "FK_Empleados_Roles_RolNombre" FOREIGN KEY ("RolNombre") REFERENCES public."Roles"("Nombre") ON DELETE CASCADE;


--
-- Name: EstacionesSismologicas FK_EstacionesSismologicas_Empleados_EmpleadoMail; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EstacionesSismologicas"
    ADD CONSTRAINT "FK_EstacionesSismologicas_Empleados_EmpleadoMail" FOREIGN KEY ("EmpleadoMail") REFERENCES public."Empleados"("Mail");


--
-- Name: EstacionesSismologicas FK_EstacionesSismologicas_Estados_EstadoNombre; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EstacionesSismologicas"
    ADD CONSTRAINT "FK_EstacionesSismologicas_Estados_EstadoNombre" FOREIGN KEY ("EstadoNombre") REFERENCES public."Estados"("Nombre") ON DELETE CASCADE;


--
-- Name: EstacionesSismologicas FK_EstacionesSismologicas_Sismografos_SismografoIdentificadorS~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."EstacionesSismologicas"
    ADD CONSTRAINT "FK_EstacionesSismologicas_Sismografos_SismografoIdentificadorS~" FOREIGN KEY ("SismografoIdentificadorSismografo") REFERENCES public."Sismografos"("IdentificadorSismografo") ON DELETE CASCADE;


--
-- Name: MotivosFueraDeServicio FK_MotivosFueraDeServicio_CambiosEstado_CambioEstadoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MotivosFueraDeServicio"
    ADD CONSTRAINT "FK_MotivosFueraDeServicio_CambiosEstado_CambioEstadoId" FOREIGN KEY ("CambioEstadoId") REFERENCES public."CambiosEstado"("Id");


--
-- Name: MotivosFueraDeServicio FK_MotivosFueraDeServicio_TiposMotivo_TipoMotivoId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MotivosFueraDeServicio"
    ADD CONSTRAINT "FK_MotivosFueraDeServicio_TiposMotivo_TipoMotivoId" FOREIGN KEY ("TipoMotivoId") REFERENCES public."TiposMotivo"("Id") ON DELETE CASCADE;


--
-- Name: OrdenesDeInspeccion FK_OrdenesDeInspeccion_Empleados_EmpleadoMail; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdenesDeInspeccion"
    ADD CONSTRAINT "FK_OrdenesDeInspeccion_Empleados_EmpleadoMail" FOREIGN KEY ("EmpleadoMail") REFERENCES public."Empleados"("Mail");


--
-- Name: OrdenesDeInspeccion FK_OrdenesDeInspeccion_EstacionesSismologicas_EstacionSismolog~; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdenesDeInspeccion"
    ADD CONSTRAINT "FK_OrdenesDeInspeccion_EstacionesSismologicas_EstacionSismolog~" FOREIGN KEY ("EstacionSismologicaCodigoEstacion") REFERENCES public."EstacionesSismologicas"("CodigoEstacion") ON DELETE CASCADE;


--
-- Name: OrdenesDeInspeccion FK_OrdenesDeInspeccion_Estados_EstadoNombre; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."OrdenesDeInspeccion"
    ADD CONSTRAINT "FK_OrdenesDeInspeccion_Estados_EstadoNombre" FOREIGN KEY ("EstadoNombre") REFERENCES public."Estados"("Nombre");


--
-- Name: Sesiones FK_Sesiones_Usuarios_UsuarioNombreUsuario; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sesiones"
    ADD CONSTRAINT "FK_Sesiones_Usuarios_UsuarioNombreUsuario" FOREIGN KEY ("UsuarioNombreUsuario") REFERENCES public."Usuarios"("NombreUsuario") ON DELETE CASCADE;


--
-- Name: Usuarios FK_Usuarios_Empleados_EmpleadoMail; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Usuarios"
    ADD CONSTRAINT "FK_Usuarios_Empleados_EmpleadoMail" FOREIGN KEY ("EmpleadoMail") REFERENCES public."Empleados"("Mail");


--
-- PostgreSQL database dump complete
--

\unrestrict fIOi76WT2yoeotlMBM4kczfKGj77QVHtCQXfhwYFU0Mlm5QKhEbJe5v8l8rxl5t

